meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    MealPlanListView,
    MealPlanDetailView,
    MealPlanDeleteView,
    MealPlanCreateView,
    MealPlanUpdateView,
)
urlpatterns = [
    path("", MealPlanListView.as_view(), name="mealplans_list"),
    path("new/", MealPlanCreateView.as_view(), name="mealplans_new"),
    path("<int:pk>", MealPlanDetailView.as_view(), name="mealplans_detail"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="mealplans_edit"),
    path("<int:pk>/delete/",MealPlanDeleteView.as_view(), name="mealplans_delete"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("mealplans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateField(null=True)

    owner = models.ForeignKey(
      USER_MODEL,
      related_name="meal_plans",
      on_delete=models.CASCADE,
      null=True,
    )

    recipes = models.ManyToManyField(
      "recipes.Recipe",
      related_name="meal_plans"
    )
    def __str__(self):
      return self.name + " created by " + str(self.owner)

meal_plans/forms.py
from django import forms
from meal_plans.models import MealPlan

class MealPlanForm(forms.ModelForm):
  class Meta:
    model = MealPlan
    fields = [
      "name",
      "author",
      "date"
    ]

meal_plans/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from meal_plans.models import MealPlan
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
# User have to login before they want to use this feature.


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "recipes", "date"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("mealplans_detail", pk=plan.id)
    # filter out the mealplans that created by the user only


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "recipes", "date"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("mealplans_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("mealplans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
  <main class="mealplans-detail">
    <div>
      <a href="{% url 'mealplans_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'mealplans_delete' mealplan.id %}">Delete</a>
    </div>
    <h2>Recipes in {{ mealplan.name }}, created by {{ user }} on {{ mealplan.date }}</h2>
    {% for recipe in mealplan.recipes.all %}
      <p>
        <a href="{% url 'recipe_detail' recipe.pk %}">
          {{ recipe.name }}</a>
      </p>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{%block pagination%}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{%endblock pagination%}

{% block content%}
  <main class="mealplan-grid">
    <a class="create-mealplan-button"
    href="{% url 'mealplans_new' %}">Create
    </a>

    {% for mealplan in mealplan_list %}
      <div class="mealplans-card">
        <h2 class="mealplans-card-title">
          <a href="{% url 'mealplans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
        <p class="mealplans-card-date">{{ mealplans.updated }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock content%}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}


{% block content %}
  <main class="mealplan-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="create-mealplan-button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}